#!/usr/bin/env python

import os
import sys

import torch
from diffusers import (
    PNDMScheduler,
    LMSDiscreteScheduler,
    DDIMScheduler,
    StableDiffusionPipeline,
    StableDiffusionImg2ImgPipeline,
    StableDiffusionInpaintPipelineLegacy,
    EulerDiscreteScheduler,
    EulerAncestralDiscreteScheduler,
)

MODEL_CACHE = "diffusers-cache"
os.makedirs(MODEL_CACHE, exist_ok=True)


pipe = StableDiffusionPipeline.from_pretrained(
    "JimDesenio/desenio-landscapes",
    cache_dir=MODEL_CACHE,
    use_auth_token=sys.argv[1],
)

PNDM = PNDMScheduler.from_config(
    "JimDesenio/desenio-landscapes",
    cache_dir=MODEL_CACHE,
    subfolder="scheduler",
    use_auth_token=sys.argv[1],
)
KLMS = LMSDiscreteScheduler.from_config(
    "JimDesenio/desenio-landscapes",
    cache_dir=MODEL_CACHE,
    subfolder="scheduler",
    use_auth_token=sys.argv[1],
)
DDIM = DDIMScheduler.from_config(
    "JimDesenio/desenio-landscapes",
    cache_dir=MODEL_CACHE,
    subfolder="scheduler",
    use_auth_token=sys.argv[1],
)
K_EULER = EulerDiscreteScheduler.from_config(
    "JimDesenio/desenio-landscapes",
    cache_dir=MODEL_CACHE,
    subfolder="scheduler",
    use_auth_token=sys.argv[1],
)
K_EULER_ANCESTRAL = EulerAncestralDiscreteScheduler.from_config(
    "JimDesenio/desenio-landscapes",
    cache_dir=MODEL_CACHE,
    subfolder="scheduler",
    use_auth_token=sys.argv[1],
)
